cache: bundler
language: ruby
rvm:
  - 2.4.6
  - 2.5.3
  - 2.6.5
env:
  global:
  - LD_LIBRARY_PATH=spec/ext
  matrix:
  - VDDK_VERSION=6.7.0
  - VDDK_VERSION=5.5.0
before_install:
  - make -C spec/ext
